services:
  proxy:
    image: ghcr.io/liamwahlstroem/proxy:latest
    container_name: proxy
    restart: always
    ports:
      - 443:443
      - 80:80
    expose:
      - 80
      - 443
  messageQueue:
    image: ghcr.io/liamwahlstroem/queue:latest
    container_name: messagequeue
    restart: always
    ports: 
      - 5672:5672
      - 15672:15672
  userService:
    image: ghcr.io/liamwahlstroem/user-service:latest
    container_name: userService
    restart: always
    volumes:
      - test
    requires:
      - messageQueue
      - proxy
  addition:
    image: ghcr.io/liamwahlstroem/addition:latest
    container_name: addition
    restart: always
    ports: 
      - 5000:5000
    volumes:
      - test
    requires:
      - messageQueue
      - proxy
      - userService
  subtract:
    image: ghcr.io/liamwahlstroem/subtract:latest
    container_name: subtract
    restart: always
    ports: 
      - 5000:5000
    volumes:
      - test
    requires:
      - messageQueue
      - proxy
      - userService
  division:
    image: ghcr.io/liamwahlstroem/division:latest
    container_name: division
    restart: always
    ports: 
      - 5000:5000
    volumes:
      - test
    requires:
      - messageQueue
      - proxy
      - userService
  multiplication:
    image: ghcr.io/liamwahlstroem/multiplication:latest
    container_name: multiplication
    restart: always
    ports: 
      - 5000:5000
    volumes:
      - test
    requires:
      - messageQueue
      - proxy
      - userService
