services:
  proxy:
  messageQueue:
    image: ghcr.io/liamwahlstroem/queue:latest
    container_name: messageQueue
    restart: always
    ports: 
      - 5672:5672
      - 15672:15672
  userService:
    image: ghcr.io/liamwahlstroem/user-service:latest
    container_name: userService
    restart: always
    volumes:
      - /test_data/user_data.json:/etc/db/user_data.json
    requires:
      - messageQueue
  login:
    image: ghcr.io/liamwahlstroem/login:latest
    container_name: login
    restart: always
    ports: 
      - 5000:5000
    requires:
      - messageQueue
      - userService
  register:
    image: ghcr.io/liamwahlstroem/register:latest
    container_name: register
    restart: always
    ports: 
      - 5000:5000
    requires:
      - messageQueue
      - userService
  addition:
    image: ghcr.io/liamwahlstroem/addition:latest
    container_name: addition
    restart: always
    ports: 
      - 5000:5000
    volumes:
      - /etc/db/addition/:/etc/db/
    requires:
      - messageQueue
      - userService
  subtract:
    image: ghcr.io/liamwahlstroem/subtract:latest
    container_name: subtract
    restart: always
    ports: 
      - 5000:5000
    volumes:
      - /etc/db/subtract/:/etc/db/
    requires:
      - messageQueue
      - userService
  division:
    image: ghcr.io/liamwahlstroem/division:latest
    container_name: division
    restart: always
    ports: 
      - 5000:5000
    volumes: 
      - /etc/db/division/:/etc/db/
    requires:
      - messageQueue
      - userService
  multiplication:
    image: ghcr.io/liamwahlstroem/multiplication:latest
    container_name: multiplication
    restart: always
    ports: 
      - 5000:5000
    volumes:
      - /etc/db/multiplication/:/etc/db/
    requires:
      - messageQueue
      - userService
