name: Multiplication Pipeline

env:
  IMAGE_NAME: multiplication

on:
  push:
    branches:
      - main
    paths:
      - 'multiplication/**'
  pull_request:
    branches:
      - main
    paths:
      - 'multiplication/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
                
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./multiplication
          push: true
          tags: ghcr.io/liamwahlstroem/${{ env.IMAGE_NAME }}:latest
