name: addition pipeline

env:
  IMAGE_NAME: addition

on:
  push:
    branches:
      - main
    paths:
      - 'addition/**'
  pull_request:
    branches:
      - main
    paths:
      - 'addition/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
                
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: ./addition/.
          push: true
          tags: ghcr.io/liamwahlstroem/${{ env.IMAGE_NAME }}:latest
