name: Subtract Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'subtract/**'
  pull_request:
    branches:
      - main
    paths:
      - 'subtract/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache  # Path for Docker layer cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        id: build_image
        uses: docker/build-push-action@v5
        with:
          context: ./subtract
          tags: myregistry/subtract:latest  # Tag image locally
          load: true  # Load the image directly to use it later
          cache-from: type=local,src=/tmp/.buildx-cache  # Use cached layers
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max  # Save updated layers

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load Docker image from build
        run: echo "Image already loaded from the previous build step"

      - name: Set up Docker Compose for Testing
        run: docker-compose -f docker-compose.test.yml up -d messageQueue userService subtract

      - name: Run Pytest tests
        run: pytest /test/subtract.test.py

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose -f docker-compose.test.yml down

  push:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./subtract
          push: true  # Push only after successful tests
          tags: ghcr.io/${{ github.repository_owner }}/subtract:latest
          cache-from: type=local,src=/tmp/.buildx-cache