name: Addition Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'addition/**'
  pull_request:
    branches:
      - main
    paths:
      - 'addition/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        id: build_image
        uses: docker/build-push-action@v5
        with:
          context: ./addition
          tags: myregistry/addition:latest
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Install dependencies
        run: pip install pytest

      - name: Set up Docker Compose for Testing
        run: docker-compose -f docker-compose.test.yml up -d messageQueue userService addition

      - name: Run Pytest tests
        run: pytest /test/addition.test.py

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose -f docker-compose.test.yml down

  push:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./addition
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/addition:latest
          cache-from: type=local,src=/tmp/.buildx-cache
